name: Latest portfolio
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  updating-portfolio:
    name: update-index-with-project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kaustubhgupta/PortfolioFy@main 
        with:
          gh_token: ${{ secrets.TOKEN }}
          stats_choice: 2
          social_links: "https://www.linkedin.com/in/ruth-l-dorton/"
          allow_footer: True
